# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        include:
          - node-version: 14.x
            reportCoverage: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm version
    - run: npm install
    - run: npm run generate-docs
    - run: npm test
    - run: npm run semantic-release-dry-run
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      if: matrix.reportCoverage
